const chatEvents = {
  CHOOSE_USER_FROM_CLIENT: 'CHOOSE_USER_FROM_CLIENT ',
  CHOOSE_USER_FROM_SERVER: 'CHOOSE_USER_FROM_SERVER',
  SEND_MESSAGE_FROM_CLIENT: 'SEND_MESSAGE_FROM_CLIENT',
  GET_MESSAGE_FROM_SERVER: 'GET_MESSAGE_FROM_SERVER',
};

export default chatEvents;
