const RoomEvents = {
  CREATE_ROOM: 'CREATE_ROOM:',
  GET_ROOM_FROM_CLIENT: 'GET_ROOM_FROM_CLIENT',
  GET_ROOM_FROM_SERVER: 'GET_ROOM_FROM_SERVER',
  CONNECT_TO_ROOM: 'CONNECT_TO_ROOM',
  USER_CONNECTED: 'USER_CONNECTED',
  GET_ROOM_STATUS_FROM_CLIENT: 'GET_ROOM_STATUS_FROM_CLIENT',
  GET_ROOM_STATUS_FROM_SERVER: 'GET_ROOM_STATUS_FROM_SERVER',
  SET_ROOM_MESSAGE_FROM_CLIENT: 'SET_ROOM_MESSAGE_FROM_CLIENT',
  START_GAME: 'START_GAME',
  GAME_BEGUN: 'GAME_BEGUN',
  CLOSE_ROOM: 'CLOSE_ROOM',
  CONNECT_TO_ROOM: 'CONNECT_TO_ROOM',
  DISCONNECT_FROM_ROOM: 'DISCONNECT_FROM_ROOM',
  GET_AVAILABLE_ROOMS: 'GET_AVAILABLE_ROOMS',
  GET_USERS_FROM_ROOM: 'GET_USERS_FROM_ROOM',
};

export default RoomEvents;
